### ISSUE TITLE
LuckyAPI requires additional updates to support Content Patch #9

### ISSUE THREAD

**Issue by kazyofloof** [ValgoBoi/LuckyAPI#23]
**Is your feature request related to a problem? Please describe.**
The modloader currently cannot support the latest content patch; simply changing the version number expected to the current one results in all floor effects being rendered as "Null" and it being impossible to start a game.

**Describe the solution you'd like**
This will require additional research into what is causing the issue particularly, and a fix deployed for said issue. This mostly serves as a note, and something to be closed once support exists. One thing of note may be the altered save structure; there are now two files, LBAL.save for save-specific information and LBAL-Stats.save for unlocked floors, total runs, and other such statistics. In addition, the implementation of extra floors might be causing issues itself.

**Additional context**
![Screenshot_20210718_125248](https://user-images.githubusercontent.com/76271195/126075669-ab81ae56-1f16-4443-b10d-3e4fd5a2025b.png)
"Start" does not start a game, rather replacing the options button with another functional Back button, oddly enough.

**Comment by kazyofloof** [comment]
The game now works fine for the most part, but the solution used has caused Comfy Pillow to no longer function.

**Comment by ValgoBoi** [comment]
Should be fixed now.
